### ISSUE TITLE
Arch Linux AUR package info for DekTec dkms drivers

### ISSUE THREAD

**Issue by nt74** [lelegard/dektec-dkms#4]
I've made an Arch Linux "Arch User Repository (AUR)" package which you can web-search with `!aur dektec-drivers-dkms` or find [here](https://aur.archlinux.org/packages/dektec-drivers-dkms).
Please feel free to add this AUR package with information for the Arch Linux users that want to laborate/test/run DekTec devices. 
I'd also like to thank You for this amazing repo which helps make installing the DekTec (dkms) drivers easy!
### Instructions for installing this package
With [yay](https://aur.archlinux.org/packages/yay):
`yay -S dektec-drivers-dkms`

Normal method:
```
git clone https://aur.archlinux.org/dektec-drivers-dkms.git
cd dektec-drivers-dkms
makepkg -si
```

**Comment by nt74** [comment]
Also made a small ArchWiki page for DekTec cards, it also points to TSDuck project for development possibilities etc.
It can be found [here](https://wiki.archlinux.org/title/DekTec_PC_add-on_cards_for_professional_digital-television)

**Comment by lelegard** [comment]
Thanks for the reference.

In your wiki, you mention your own [AUR package "tsduck-git" for TSDuck](https://aur.archlinux.org/packages/tsduck-git). Please note that there has been [another AUR package "tsduck" for TSDuck](https://aur.archlinux.org/packages/tsduck) which is maintained by @piotrserafin. It has been there since 2018 and is kept up-to-date by @piotrserafin (version 3.33 as of today). It is better to keep only one source of package for the same project.

**Comment by nt74** [comment]
I can add that to the page, even it is of no huge difference my package is working directly with the git package, there are plenty of packages in the AUR space with both releases and git-releases.
Also the first package already has another older AUR package called ["dektec-dkms"](https://aur.archlinux.org/packages/dektec-dkms) which I tried to contact the user but with no success. It is afterall work in progress with most things, of course I will take it to consideration and revise all documentation and package issues.

**Comment by lelegard** [comment]
Honestly, there should be only one dektec dkms drivers package, and it should be maintained by Dektec, for all distros. My dektec-dkms project was intented to be temporary, as an interim for a Dektec version to come. I proposed several times to Dektec to take over, but they prefer to keep their LinuxSDK .zip archive. This is strange since their Windows packaging is quite good while the Linux one is poor.

Software packaging is an important topic which is underestimated by many. I started several packaging projects for other software. Some were accepted and integrated into the parent project (such as SRT for Windows or VATek for Linux and macOS), some others are still independent (such as RIST packaging for Windows and Dektec for Linux).

**Comment by nt74** [comment]
Yes I totally agree, but as We both know from experience there are a plethora of manufacturers on the market that somehow do not put too much resources towards platforms like Linux.
I was also pointing this out to DekTec support and also gave it quite some time to unfold if any package would be available for Linux distros. Those are usually the ones You already have included like DEB- and RPM-packages.
Since I personally work with Arch Linux and Ubuntu, I usually try to find out community (user) driven AUR space.

As for DekTec taking responsibility of building a dkms-driver (and maybe 1-3 mainstream applications) for Linux would really help people working with digital-television solutions a lot. DekTec cards can be great tools for monitoring as well. Maybe they think it is too much to manage since there are a lot of different Linux distro's out there. Maybe focus on the most popular ones?

Once again many thanks @lelegard for Your great work, I really appreciate it!

**Comment by nt74** [comment]
I am closing this topic @lelegard, thanks for the quick response.
